punching-bags = [
    { x = -96.5, y = -60.0, z = -154.5 },
    { x = -96.5, y = -60.0, z = -156.5 },
    { x = -96.5, y = -60.0, z = -158.5 },
    { x = -96.5, y = -60.0, z = -160.5 },
    { x = -96.5, y = -60.0, z = -162.5 },
    { x = -96.5, y = -60.0, z = -164.5 }
]